# Generated by Django 6.0.3 on 2026-04-12 21:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du pack')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('max_etudiants', models.IntegerField(default=100, verbose_name="Nombre max d'étudiants")),
                ('max_cours', models.IntegerField(default=50, verbose_name='Nombre max de cours')),
                ('stockage_gb', models.IntegerField(default=5, verbose_name='Stockage (GB)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage (plus grand = en haut)")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ordre', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du cours')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cours/images/', verbose_name='Image du cours')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Cours actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordre', 'date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ExerciceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_exercice', models.CharField(choices=[('quiz', 'Quiz (QCM)'), ('pratique', 'Exercice pratique'), ('etude_cas', 'Étude de cas'), ('redaction', 'Rédaction courte'), ('code', 'Exercice de code')], max_length=20)),
                ('duree', models.IntegerField(help_text='Durée en minutes')),
                ('consignes', models.TextField()),
                ('questions_json', models.JSONField(blank=True, null=True)),
                ('demarre', models.BooleanField(default=False)),
                ('date_demarrage', models.DateTimeField(blank=True, null=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du quiz')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('temps_limite', models.IntegerField(default=30, verbose_name='Temps limite (minutes)')),
                ('tentative_max', models.IntegerField(default=1, verbose_name='Nombre maximum de tentatives')),
                ('note_pour_reussir', models.FloatField(default=10, verbose_name='Note pour réussir (sur 20)')),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='Mélanger les questions')),
                ('feedback_immediat', models.BooleanField(default=True, verbose_name='Feedback immédiat')),
                ('date_ouverture', models.DateTimeField(verbose_name="Date d'ouverture")),
                ('date_fermeture', models.DateTimeField(blank=True, null=True, verbose_name='Date de fermeture')),
                ('actif', models.BooleanField(default=True, verbose_name='Quiz actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('pays', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays')),
                ('role', models.CharField(blank=True, choices=[('super_admin', 'Super Administrateur'), ('admin_ecole', 'Administrateur École'), ('enseignant', 'Enseignant'), ('etudiant', 'Étudiant')], max_length=20, null=True, verbose_name='Rôle')),
                ('email_valide', models.BooleanField(default=False, verbose_name='Email validé')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='CoursProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du cours')),
                ('description', models.TextField(verbose_name='Description')),
                ('objectifs', models.TextField(blank=True, null=True, verbose_name='Objectifs pédagogiques')),
                ('actif', models.BooleanField(default=True, verbose_name='Cours actif')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', max_length=20, verbose_name='Statut du cours')),
                ('mode_programmation', models.CharField(choices=[('recurrent', 'Hebdomadaire récurrent'), ('personnalise', 'Personnalisé par semaine')], default='recurrent', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('enseignant', models.ForeignKey(blank=True, limit_choices_to={'role': 'enseignant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_assignes', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant responsable')),
            ],
            options={
                'ordering': ['date_debut', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name="Nom de l'école")),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Identifiant URL')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('description', models.TextField(verbose_name='Description')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='Cameroun', max_length=100, verbose_name='Pays')),
                ('quartier', models.CharField(blank=True, max_length=200, null=True, verbose_name='Quartier')),
                ('numero_agrement', models.CharField(blank=True, max_length=100, null=True, verbose_name="Numéro d'agrément")),
                ('agrement_valide', models.BooleanField(default=False, verbose_name='Agrément validé')),
                ('actif', models.BooleanField(default=True, verbose_name='École active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('banniere', models.ImageField(blank=True, null=True, upload_to='ecoles/bannieres/', verbose_name='Bannière')),
                ('abonnement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.abonnement', verbose_name="Pack d'abonnement")),
                ('admin_ecole', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecole_admin', to=settings.AUTH_USER_MODEL, verbose_name="Administrateur de l'école")),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la filière')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('public', models.BooleanField(default=True, verbose_name='Afficher sur la page publique')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='website.ecole')),
            ],
            options={
                'ordering': ['ordre', 'nom'],
                'unique_together': {('ecole', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='GroupeDevoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du groupe')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('membres', models.ManyToManyField(related_name='groupes_devoir', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ecoles/galerie/')),
                ('titre', models.CharField(blank=True, max_length=200, null=True)),
                ('ordre', models.IntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie_images', to='website.ecole')),
            ],
            options={
                'ordering': ['ordre', '-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='MessagePrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Message')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='website.conversation')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('rappel_cours', 'Rappel de cours'), ('nouveau_cours', 'Nouveau cours'), ('nouveau_message', 'Nouveau message'), ('reponse_forum', 'Réponse sur le forum')], max_length=50)),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('lien', models.CharField(blank=True, max_length=500, null=True, verbose_name='Lien')),
                ('lu', models.BooleanField(default=False, verbose_name='Lue')),
                ('email_envoye', models.BooleanField(default=False, verbose_name='Email envoyé')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_question', models.CharField(choices=[('qcm', 'Choix multiples'), ('vrai_faux', 'Vrai/Faux'), ('reponse_courte', 'Réponse courte'), ('numerique', 'Numérique'), ('appariement', 'Appariement'), ('redaction', 'Rédaction')], max_length=20, verbose_name='Type de question')),
                ('enonce', models.TextField(verbose_name='Énoncé de la question')),
                ('points', models.FloatField(default=1, verbose_name='Points')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('feedback_general', models.TextField(blank=True, null=True, verbose_name='Feedback général')),
                ('template', models.JSONField(blank=True, null=True, verbose_name='Template pour questions aléatoires')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='website.quiz')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ReponseExercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_json', models.JSONField(default=dict)),
                ('note', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='website.exerciceapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ReponsePossible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(verbose_name='Texte de la réponse')),
                ('est_correcte', models.BooleanField(default=False, verbose_name='Est correcte')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback spécifique')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='website.question')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la séance')),
                ('description', models.TextField(blank=True, null=True)),
                ('type_seance', models.CharField(choices=[('fichier', 'Fichier (Document)'), ('visio', 'Visio-conférence'), ('quiz', 'Quiz'), ('devoir', 'Devoir')], max_length=20)),
                ('jour', models.CharField(blank=True, max_length=20, null=True)),
                ('heure', models.TimeField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='cours/fichiers/')),
                ('lien_video', models.URLField(blank=True, null=True)),
                ('lien_visio', models.URLField(blank=True, null=True)),
                ('visio_date', models.DateTimeField(blank=True, null=True)),
                ('visio_enregistrement', models.FileField(blank=True, null=True, upload_to='cours/enregistrements/')),
                ('ordre', models.IntegerField(default=0)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='website.cours')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.quiz')),
            ],
            options={
                'ordering': ['ordre', 'visio_date', 'heure'],
            },
        ),
        migrations.CreateModel(
            name='SeanceProgrammee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la séance')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type_seance', models.CharField(choices=[('visio', 'Visioconférence (BigBlueButton)'), ('asynchrone', 'Séance asynchrone (Vidéo + Document)'), ('integration', "Activité d'intégration (Projet long)"), ('correction', 'Séance de correction'), ('presentation', 'Présentation / Soutenance')], max_length=30, verbose_name='Type de séance')),
                ('jour', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], verbose_name='Jour')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('duree_estimee', models.IntegerField(default=30, help_text='Durée estimée en minutes')),
                ('note_max', models.FloatField(default=20, help_text='Note maximale')),
                ('lien_visio', models.URLField(blank=True, null=True, verbose_name='Lien BigBlueButton')),
                ('enregistrement_url', models.URLField(blank=True, null=True, verbose_name="URL de l'enregistrement")),
                ('enregistrement_disponible_jusqua', models.DateTimeField(blank=True, null=True)),
                ('contenu_texte', models.TextField(blank=True, verbose_name='Contenu texte')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='seances/fichiers/')),
                ('lien_externe', models.URLField(blank=True, null=True)),
                ('objectifs', models.TextField(blank=True, null=True, verbose_name='Objectifs pédagogiques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances_programmees', to='website.coursprogramme')),
                ('quiz_associe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.quiz')),
            ],
            options={
                'ordering': ['ordre', 'jour', 'heure_debut'],
            },
        ),
        migrations.AddField(
            model_name='exerciceapplication',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='website.seanceprogrammee'),
        ),
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_devoir', models.CharField(choices=[('document', 'Dépôt de document'), ('projet', 'Projet'), ('code', 'Code'), ('presentation', 'Présentation')], max_length=20)),
                ('consignes', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_limite', models.DateTimeField()),
                ('note_max', models.FloatField(default=20)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs', to='website.seanceprogrammee')),
            ],
        ),
        migrations.CreateModel(
            name='SoumissionDevoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_reponse', models.TextField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='devoirs/soumissions/')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('note', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='website.devoir')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FichierSoumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='devoirs/soumissions/')),
                ('nom_original', models.CharField(max_length=255)),
                ('taille', models.IntegerField()),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('soumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='website.soumissiondevoir')),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la spécialité (ex: Réseaux Niveau 1)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('cle_inscription', models.CharField(blank=True, max_length=50, unique=True, verbose_name="Clé d'inscription")),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialites', to='website.filiere')),
            ],
            options={
                'ordering': ['ordre', 'nom'],
                'unique_together': {('filiere', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizs', to='website.specialite'),
        ),
        migrations.AddField(
            model_name='coursprogramme',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_programmes', to='website.specialite'),
        ),
        migrations.AddField(
            model_name='cours',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='website.specialite'),
        ),
        migrations.CreateModel(
            name='SujetForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_forum', models.CharField(choices=[('ecole', 'Forum École'), ('specialite', 'Forum Spécialité')], max_length=20)),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du sujet')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets_forum', to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sujets_forum', to='website.ecole')),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sujets_forum', to='website.specialite')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MessageForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Message')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_forum', to=settings.AUTH_USER_MODEL)),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='website.sujetforum')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='TentativeQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('note', models.FloatField(blank=True, null=True, verbose_name='Note obtenue')),
                ('tentative_numero', models.IntegerField(default=1, verbose_name='Numéro de tentative')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives_quiz', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to='website.quiz')),
            ],
            options={
                'unique_together': {('quiz', 'etudiant', 'tentative_numero')},
            },
        ),
        migrations.CreateModel(
            name='ReponseEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_texte', models.TextField(blank=True, null=True, verbose_name='Réponse texte')),
                ('reponse_id', models.IntegerField(blank=True, null=True, verbose_name='ID de la réponse choisie')),
                ('est_correcte', models.BooleanField(default=False, verbose_name='Est correcte')),
                ('points_obtenus', models.FloatField(default=0, verbose_name='Points obtenus')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback personnalisé')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.question')),
                ('tentative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='website.tentativequiz')),
            ],
        ),
        migrations.CreateModel(
            name='EnseignantEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignants', to='website.ecole')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_ecoles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('enseignant', 'ecole')},
            },
        ),
        migrations.CreateModel(
            name='ParticipantCoursProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloque', models.BooleanField(default=False, verbose_name='Bloqué')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='website.coursprogramme')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_programmes_participes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cours', 'etudiant')},
            },
        ),
        migrations.CreateModel(
            name='ProgressionEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_activite', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='website.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to=settings.AUTH_USER_MODEL)),
                ('seance_terminees', models.ManyToManyField(blank=True, related_name='terminee_par', to='website.seance')),
            ],
            options={
                'unique_together': {('etudiant', 'cours')},
            },
        ),
        migrations.CreateModel(
            name='PresenceSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('vu', models.BooleanField(default=False, verbose_name='Séance vue')),
                ('date_vu', models.DateTimeField(blank=True, null=True)),
                ('temps_connecte', models.IntegerField(default=0)),
                ('note', models.FloatField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='website.seanceprogrammee')),
            ],
            options={
                'unique_together': {('seance', 'etudiant')},
            },
        ),
        migrations.CreateModel(
            name='NoteEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(verbose_name='Note')),
                ('note_max', models.FloatField(default=20, verbose_name='Note maximale')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('date_attribution', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='website.coursprogramme')),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_donnees', to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('seance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='website.seanceprogrammee')),
            ],
            options={
                'unique_together': {('etudiant', 'cours', 'seance')},
            },
        ),
        migrations.CreateModel(
            name='DepotPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='presentations/', verbose_name='Fichier (PPT, PDF)')),
                ('lien_video', models.URLField(blank=True, null=True, verbose_name='Lien vidéo')),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('note', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='website.seanceprogrammee')),
            ],
            options={
                'unique_together': {('seance', 'etudiant')},
            },
        ),
        migrations.CreateModel(
            name='InscriptionEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL)),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='website.specialite')),
            ],
            options={
                'unique_together': {('etudiant', 'specialite')},
            },
        ),
    ]
