# Generated by Django 6.0.3 on 2026-05-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationplateforme',
            name='auto_publication_delai_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='heure_debut_pause',
            field=models.CharField(blank=True, default='22:00', help_text='Format HH:MM', max_length=5),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='heure_fin_pause',
            field=models.CharField(blank=True, default='08:00', help_text='Format HH:MM', max_length=5),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='stat1_label',
            field=models.CharField(blank=True, default='Étudiants', max_length=100),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='stat1_valeur_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='stat1_valeur_fixe',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='stat2_label',
            field=models.CharField(blank=True, default='Formations', max_length=100),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='stat2_valeur_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='stat2_valeur_fixe',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='stat3_label',
            field=models.CharField(blank=True, default='Épreuves', max_length=100),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='stat3_valeur_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='stat3_valeur_fixe',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='stat4_label',
            field=models.CharField(blank=True, default='Partenaires', max_length=100),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='stat4_valeur_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='stat4_valeur_fixe',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
