# Generated by Django 6.0.3 on 2026-04-13 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='date_creation',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='date_fermeture',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='date_ouverture',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='feedback_immediat',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='note_pour_reussir',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='shuffle_questions',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='specialite',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='temps_limite',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='tentative_max',
        ),
        migrations.AddField(
            model_name='quiz',
            name='date_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='date_publication',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='resultats_publies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='seance',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quizs_de_la_seance', to='website.seanceprogrammee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='titre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='seance',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_quiz', to='website.quiz'),
        ),
    ]
