# Generated by Django 6.0.3 on 2026-05-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_configurationplateforme_auto_publication_delai_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationplateforme',
            name='nb_ecoles_accueil',
            field=models.IntegerField(default=6, help_text="Nombre d'écoles à afficher sur la page d'accueil"),
        ),
    ]
