# Generated by Django 6.0.3 on 2026-05-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_configurationplateforme_nb_ecoles_accueil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationplateforme',
            options={'verbose_name': 'Configuration de la plateforme', 'verbose_name_plural': 'Configuration de la plateforme'},
        ),
        migrations.RenameField(
            model_name='configurationplateforme',
            old_name='section_footer_visible',
            new_name='afficher_formations_gratuites_badge',
        ),
        migrations.RemoveField(
            model_name='configurationplateforme',
            name='footer_description',
        ),
        migrations.RemoveField(
            model_name='configurationplateforme',
            name='footer_email',
        ),
        migrations.RemoveField(
            model_name='configurationplateforme',
            name='heure_debut_pause',
        ),
        migrations.RemoveField(
            model_name='configurationplateforme',
            name='heure_fin_pause',
        ),
        migrations.RemoveField(
            model_name='configurationplateforme',
            name='slogan',
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='afficher_nb_ventes_formations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='afficher_note_formations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='afficher_prix_formations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='auto_publication_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='couleur_accent',
            field=models.CharField(default='#10b981', max_length=7),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='footer_email_contact',
            field=models.EmailField(blank=True, default='contact@academienet.cm', max_length=254),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='footer_facebook',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='footer_instagram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='footer_linkedin',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='footer_texte',
            field=models.TextField(blank=True, default='La plateforme qui connecte les écoles, formateurs et étudiants.'),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='footer_twitter',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='footer_youtube',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='hero_afficher_stats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='hero_bouton1_lien',
            field=models.CharField(default='/inscription/', max_length=200),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='hero_bouton1_texte',
            field=models.CharField(default='Commencer gratuitement', max_length=80),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='hero_bouton2_lien',
            field=models.CharField(default='/formations/', max_length=200),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='hero_bouton2_texte',
            field=models.CharField(default='Explorer les formations', max_length=80),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='hero_description',
            field=models.TextField(default='Écoles, formations, épreuves — tout au même endroit.'),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='config/hero/'),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='hero_titre',
            field=models.CharField(default="La plateforme éducative de l'Afrique", max_length=200),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='hero_titre_accent',
            field=models.CharField(default='Apprenez. Enseignez. Réussissez.', max_length=100),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='hero_video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='message_maintenance',
            field=models.TextField(blank=True, default='Site en maintenance. Revenez bientôt.'),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='mode_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='section_audience_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='section_comment_ca_marche_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='section_cta_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='section_ecoles_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='section_newsletter_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='section_services_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='slogan_site',
            field=models.CharField(blank=True, default="La plateforme éducative de l'Afrique", max_length=200),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='sous_titre_section_cta',
            field=models.CharField(blank=True, default='Rejoignez la plus grande communauté éducative moderne', max_length=300),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='sous_titre_section_epreuves',
            field=models.CharField(blank=True, default='Bac, BEPC, Probatoire, Concours — tout y est', max_length=200),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='sous_titre_section_formations',
            field=models.CharField(blank=True, default='Découvrez nos meilleures formations sélectionnées pour vous', max_length=200),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='titre_section_cta',
            field=models.CharField(default="Prêt à transformer l'éducation en Afrique ?", max_length=200),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='titre_section_ecoles',
            field=models.CharField(default='Nos écoles partenaires', max_length=100),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='titre_section_epreuves',
            field=models.CharField(default="Bibliothèque d'épreuves", max_length=100),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='titre_section_formations',
            field=models.CharField(default='Formations en vedette', max_length=100),
        ),
        migrations.AddField(
            model_name='configurationplateforme',
            name='titre_section_temoignages',
            field=models.CharField(default='Ils nous font confiance', max_length=100),
        ),
        migrations.AlterField(
            model_name='configurationplateforme',
            name='couleur_principale',
            field=models.CharField(default='#1e3a8a', max_length=7),
        ),
        migrations.AlterField(
            model_name='configurationplateforme',
            name='couleur_secondaire',
            field=models.CharField(default='#f59e0b', max_length=7),
        ),
        migrations.AlterField(
            model_name='configurationplateforme',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='config/favicon/'),
        ),
        migrations.AlterField(
            model_name='configurationplateforme',
            name='footer_adresse',
            field=models.CharField(blank=True, default='Douala, Cameroun', max_length=200),
        ),
        migrations.AlterField(
            model_name='configurationplateforme',
            name='footer_telephone',
            field=models.CharField(blank=True, default='+237 6 XX XX XX XX', max_length=30),
        ),
        migrations.AlterField(
            model_name='configurationplateforme',
            name='formations_tri',
            field=models.CharField(choices=[('-date_publication', 'Plus récentes'), ('-nb_ventes', 'Plus vendues'), ('-note_moyenne', 'Mieux notées')], default='-date_publication', max_length=30),
        ),
        migrations.AlterField(
            model_name='configurationplateforme',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='config/logo/'),
        ),
        migrations.AlterField(
            model_name='configurationplateforme',
            name='nb_ecoles_accueil',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='configurationplateforme',
            name='nb_epreuves_accueil',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='configurationplateforme',
            name='nb_formations_accueil',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='configurationplateforme',
            name='section_partenaires_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configurationplateforme',
            name='stat1_label',
            field=models.CharField(default='Écoles partenaires', max_length=50),
        ),
        migrations.AlterField(
            model_name='configurationplateforme',
            name='stat1_valeur_fixe',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='configurationplateforme',
            name='stat2_label',
            field=models.CharField(default='Formations disponibles', max_length=50),
        ),
        migrations.AlterField(
            model_name='configurationplateforme',
            name='stat2_valeur_fixe',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='configurationplateforme',
            name='stat3_label',
            field=models.CharField(default='Épreuves téléchargées', max_length=50),
        ),
        migrations.AlterField(
            model_name='configurationplateforme',
            name='stat3_valeur_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configurationplateforme',
            name='stat3_valeur_fixe',
            field=models.CharField(blank=True, default='5 000+', max_length=20),
        ),
        migrations.AlterField(
            model_name='configurationplateforme',
            name='stat4_label',
            field=models.CharField(default='Étudiants inscrits', max_length=50),
        ),
        migrations.AlterField(
            model_name='configurationplateforme',
            name='stat4_valeur_fixe',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
