# Generated by Django 6.0.3 on 2026-05-29 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_configurationplateforme_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilisateurBloqueForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_blocage', models.DateTimeField(auto_now_add=True)),
                ('raison', models.TextField(blank=True, null=True)),
                ('bloque_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocages_effectues', to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='website.forum')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forums_bloques', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisateur bloqué',
                'verbose_name_plural': 'Utilisateurs bloqués',
                'unique_together': {('forum', 'utilisateur')},
            },
        ),
    ]
