# Generated by Django 6.0.3 on 2026-05-29 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_utilisateurbloqueforum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateurbloqueforum',
            old_name='raison',
            new_name='motif',
        ),
        migrations.AddField(
            model_name='utilisateurbloqueforum',
            name='date_deblocage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateurbloqueforum',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocages', to='website.forum'),
        ),
        migrations.AlterField(
            model_name='utilisateurbloqueforum',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocages_forum', to=settings.AUTH_USER_MODEL),
        ),
    ]
