# Generated by Django 6.0.3 on 2026-05-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_raison_utilisateurbloqueforum_motif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationmessagerie',
            name='sujet_jour_actif',
            field=models.BooleanField(default=False),
        ),
    ]
