# Generated by Django 6.0.3 on 2026-05-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_configurationmessagerie_sujet_jour_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationmessagerie',
            name='forum_messages_par_page',
            field=models.IntegerField(default=20),
        ),
    ]
