# Generated by Django 6.0.3 on 2026-06-04 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_configurationmessagerie_forum_messages_par_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='paiement_desactive',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AbonnementUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abonnement', models.CharField(choices=[('mensuel', 'Mensuel (500 FCFA)'), ('trimestriel', 'Trimestriel (1500 FCFA)')], default='mensuel', max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('annule', 'Annulé'), ('essai', "Période d'essai")], default='essai', max_length=20)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin_essai', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('paiement_oblige', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement_utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement utilisateur',
                'verbose_name_plural': 'Abonnements utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('abonnement', 'Abonnement'), ('formation', 'Achat formation'), ('epreuve', 'Achat épreuve')], max_length=20)),
                ('montant', models.IntegerField()),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('moyen_paiement', models.CharField(blank=True, choices=[('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money'), ('wave', 'Wave'), ('carte', 'Carte bancaire')], max_length=20, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_transaction'],
            },
        ),
    ]
