# Generated by Django 6.0.3 on 2026-06-15 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_utilisateur_paiement_desactive_abonnementutilisateur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['ordre'], 'verbose_name': 'Réponse possible'},
        ),
        migrations.AlterModelOptions(
            name='exercice',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Exercice'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['ordre'], 'verbose_name': 'Question'},
        ),
        migrations.AlterModelOptions(
            name='reponseetudiant',
            options={'verbose_name': 'Réponse étudiant'},
        ),
        migrations.AlterModelOptions(
            name='soumissionexercice',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Soumission'},
        ),
        migrations.AlterUniqueTogether(
            name='soumissionexercice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='answer',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercice',
            name='afficher_correction_immediate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercice',
            name='afficher_note_immediate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exercice',
            name='correction_publiee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercice',
            name='est_lance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercice',
            name='lance_a',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercice',
            name='melanger_questions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exercice',
            name='melanger_reponses',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exercice',
            name='multi_reponse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercice',
            name='nb_tentatives_max',
            field=models.PositiveIntegerField(default=1, help_text='0 = tentatives illimitées'),
        ),
        migrations.AddField(
            model_name='exercice',
            name='resultats_publies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='explication',
            field=models.TextField(blank=True, help_text='Affiché après la correction'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercices/questions/'),
        ),
        migrations.AddField(
            model_name='question',
            name='type_question',
            field=models.CharField(choices=[('qcm', 'QCM — une seule réponse'), ('multi', 'Choix multiples'), ('vrai_faux', 'Vrai / Faux'), ('texte_libre', 'Texte libre')], default='qcm', max_length=20),
        ),
        migrations.AddField(
            model_name='reponseetudiant',
            name='points_obtenus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='reponseetudiant',
            name='reponses_choisies',
            field=models.ManyToManyField(blank=True, related_name='reponses_multiples', to='website.answer'),
        ),
        migrations.AddField(
            model_name='soumissionexercice',
            name='nb_tentative',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='soumissionexercice',
            name='note_sur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='type_exercice',
            field=models.CharField(choices=[('qcm', 'QCM'), ('vrai_faux', 'Vrai / Faux'), ('texte_trous', 'Texte à trous'), ('reponse_courte', 'Réponse courte'), ('redaction', 'Rédaction'), ('depot_fichier', 'Dépôt de fichier'), ('code', 'Code'), ('etude_cas', 'Étude de cas')], default='qcm', max_length=20),
        ),
        migrations.AlterField(
            model_name='reponseetudiant',
            name='reponse_choisie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses_uniques', to='website.answer'),
        ),
        migrations.CreateModel(
            name='SauvegardeQCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnees_json', models.JSONField(default=dict)),
                ('date_sauvegarde', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.exercice')),
            ],
            options={
                'verbose_name': 'Sauvegarde QCM',
                'unique_together': {('etudiant', 'exercice')},
            },
        ),
    ]
