# Generated by Django 6.0.3 on 2026-06-17 06:05

import django.db.models.deletion
import website.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_answer_options_alter_exercice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoixSousQuestionEtudeCas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=500)),
                ('est_correct', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Choix sous-question',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ConsigneDepotFichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField()),
                ('extensions_autorisees', models.CharField(default='pdf,doc,docx,jpg,png,zip', help_text='Extensions séparées par des virgules, sans le point', max_length=200)),
                ('taille_max_mo', models.PositiveIntegerField(default=10)),
                ('nb_fichiers_max', models.PositiveIntegerField(default=1)),
                ('document_ressource', models.FileField(blank=True, null=True, upload_to='exercices/depot/ressources/')),
                ('grille_correction', models.TextField(blank=True, help_text='Un critère par ligne')),
                ('exercice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='depot_fichier', to='website.exercice')),
            ],
            options={
                'verbose_name': 'Consigne dépôt fichier',
            },
        ),
        migrations.CreateModel(
            name='ConsigneRedaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.TextField()),
                ('nb_mots_min', models.PositiveIntegerField(default=0, help_text='0 = pas de minimum')),
                ('nb_mots_max', models.PositiveIntegerField(default=0, help_text='0 = pas de maximum')),
                ('criteres_evaluation', models.TextField(blank=True, help_text='Un critère par ligne, ex: Orthographe (4pts), Structure (3pts)...')),
                ('document_ressource', models.FileField(blank=True, null=True, upload_to='exercices/redaction/')),
                ('exercice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redaction', to='website.exercice')),
            ],
            options={
                'verbose_name': 'Consigne de rédaction',
            },
        ),
        migrations.CreateModel(
            name='CorrectionDepotFichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_donnee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('fichier_annote', models.FileField(blank=True, null=True, upload_to='exercices/depot/annotations/')),
                ('date_correction', models.DateTimeField(blank=True, null=True)),
                ('corrige_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depots_corriges', to=settings.AUTH_USER_MODEL)),
                ('soumission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction_depot', to='website.soumissionexercice')),
            ],
            options={
                'verbose_name': 'Correction dépôt fichier',
            },
        ),
        migrations.CreateModel(
            name='EtudeCas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexte', models.TextField(help_text='Présentation du cas / scénario')),
                ('document_cas', models.FileField(blank=True, null=True, upload_to='exercices/etude_cas/')),
                ('image_cas', models.ImageField(blank=True, null=True, upload_to='exercices/etude_cas/images/')),
                ('exercice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etude_cas', to='website.exercice')),
            ],
            options={
                'verbose_name': 'Étude de cas',
            },
        ),
        migrations.CreateModel(
            name='FichierDepose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=website.models._depot_etudiant_upload_path)),
                ('nom_original', models.CharField(blank=True, max_length=255)),
                ('taille', models.BigIntegerField(default=0)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('soumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers_deposes', to='website.soumissionexercice')),
            ],
            options={
                'verbose_name': 'Fichier déposé',
                'ordering': ['date_depot'],
            },
        ),
        migrations.CreateModel(
            name='QuestionReponseCourte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercices/reponse_courte/')),
                ('reponses_acceptees', models.TextField(help_text='Une réponse acceptée par ligne (insensible à la casse et aux accents)')),
                ('sensible_casse', models.BooleanField(default=False, help_text='Respecter majuscules/minuscules')),
                ('explication', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=1)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_courtes', to='website.exercice')),
            ],
            options={
                'verbose_name': 'Question réponse courte',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ReponseCourteEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_donnee', models.CharField(blank=True, max_length=500)),
                ('est_correcte', models.BooleanField(default=False)),
                ('points_obtenus', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.questionreponsecourte')),
                ('soumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_courtes', to='website.soumissionexercice')),
            ],
            options={
                'verbose_name': 'Réponse courte étudiant',
            },
        ),
        migrations.CreateModel(
            name='ReponseRedaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_redige', models.TextField(blank=True)),
                ('nb_mots', models.PositiveIntegerField(default=0)),
                ('note_donnee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commentaire_correcteur', models.TextField(blank=True)),
                ('date_correction', models.DateTimeField(blank=True, null=True)),
                ('corrige_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redactions_corrigees', to=settings.AUTH_USER_MODEL)),
                ('soumission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redaction_reponse', to='website.soumissionexercice')),
            ],
            options={
                'verbose_name': 'Réponse rédaction',
            },
        ),
        migrations.CreateModel(
            name='SousQuestionEtudeCas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('type_question', models.CharField(choices=[('texte_libre', 'Texte libre (correction manuelle)'), ('qcm', 'QCM (correction auto)')], default='texte_libre', max_length=20)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=1)),
                ('etude_cas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_questions', to='website.etudecas')),
            ],
            options={
                'verbose_name': 'Sous-question étude de cas',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ReponseSousQuestionEtudeCas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_texte', models.TextField(blank=True)),
                ('est_correcte', models.BooleanField(default=False)),
                ('points_obtenus', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('choix_selectionne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.choixsousquestionetudecas')),
                ('soumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_etude_cas', to='website.soumissionexercice')),
                ('sous_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sousquestionetudecas')),
            ],
            options={
                'verbose_name': 'Réponse sous-question étude de cas',
            },
        ),
        migrations.AddField(
            model_name='choixsousquestionetudecas',
            name='sous_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='website.sousquestionetudecas'),
        ),
        migrations.CreateModel(
            name='TexteATrous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_brut', models.TextField(help_text='Utilisez {{1}}, {{2}}, etc. pour marquer les trous. Ex: Le {{1}} est la capitale de la {{2}}.')),
                ('exercice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='texte_a_trous', to='website.exercice')),
            ],
            options={
                'verbose_name': 'Texte à trous',
            },
        ),
        migrations.CreateModel(
            name='TrouReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Correspond à {{N}} dans le texte')),
                ('reponses_acceptees', models.TextField(help_text='Une réponse acceptée par ligne (insensible à la casse)')),
                ('points', models.PositiveIntegerField(default=1)),
                ('texte_a_trous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trous', to='website.texteatrous')),
            ],
            options={
                'verbose_name': 'Réponse de trou',
                'ordering': ['numero'],
                'unique_together': {('texte_a_trous', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ReponseTrouEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_donnee', models.CharField(blank=True, max_length=300)),
                ('est_correcte', models.BooleanField(default=False)),
                ('points_obtenus', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('soumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_trous', to='website.soumissionexercice')),
                ('trou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.troureponse')),
            ],
            options={
                'verbose_name': 'Réponse trou étudiant',
            },
        ),
    ]
