# Generated by Django 6.0.3 on 2026-06-17 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_choixsousquestionetudecas_consignedepotfichier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ressourceseance',
            options={'ordering': ['ordre', 'date_ajout'], 'verbose_name': 'Ressource de séance'},
        ),
        migrations.AlterModelOptions(
            name='seancevisio',
            options={'verbose_name': 'Séance visio'},
        ),
        migrations.AlterField(
            model_name='correctionseance',
            name='seance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction_seance', to='website.seancebase'),
        ),
        migrations.AlterField(
            model_name='ressourceseance',
            name='type_ressource',
            field=models.CharField(choices=[('fichier', 'Fichier'), ('lien', 'Lien externe')], default='fichier', max_length=10),
        ),
        migrations.CreateModel(
            name='SeanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrige_texte', models.TextField(blank=True, help_text='Corrigé rédigé directement')),
                ('corrige_fichier', models.FileField(blank=True, null=True, upload_to='seances/corrections/fichiers/')),
                ('corrige_video_url', models.URLField(blank=True, help_text='Lien vidéo de correction (YouTube, etc.)')),
                ('points_cles', models.TextField(blank=True, help_text='Un point clé par ligne')),
                ('publie', models.BooleanField(default=False)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('seance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seance_correction', to='website.seancebase')),
                ('seance_corrigee', models.ForeignKey(blank=True, help_text='La séance (devoir/exercice) que cette correction couvre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_associees', to='website.seancebase')),
            ],
            options={
                'verbose_name': 'Configuration séance de correction',
            },
        ),
        migrations.CreateModel(
            name='VueCorrectionEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vue', models.DateTimeField(auto_now_add=True)),
                ('correction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vues', to='website.seancecorrection')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vue correction étudiant',
                'unique_together': {('correction', 'etudiant')},
            },
        ),
    ]
